// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARXPnYGdsz4n-OE4SFJqJH7-6jgClOzOY',
    appId: '1:29862490445:web:9821929467672a6c2f8704',
    messagingSenderId: '29862490445',
    projectId: 'walkathan-51d40',
    authDomain: 'walkathan-51d40.firebaseapp.com',
    storageBucket: 'walkathan-51d40.firebasestorage.app',
    measurementId: 'G-ERQ8JF5HEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYtq__0klHCLc-iHCegLpMr8u1M1H8a5U',
    appId: '1:29862490445:android:ec3ed804221d7fca2f8704',
    messagingSenderId: '29862490445',
    projectId: 'walkathan-51d40',
    storageBucket: 'walkathan-51d40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyzqSAah1XelqQnnBuY076HsO4lqW_ldg',
    appId: '1:29862490445:ios:ebd5cd93fb5b49582f8704',
    messagingSenderId: '29862490445',
    projectId: 'walkathan-51d40',
    storageBucket: 'walkathan-51d40.firebasestorage.app',
    iosBundleId: 'com.example.walkathan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyzqSAah1XelqQnnBuY076HsO4lqW_ldg',
    appId: '1:29862490445:ios:ebd5cd93fb5b49582f8704',
    messagingSenderId: '29862490445',
    projectId: 'walkathan-51d40',
    storageBucket: 'walkathan-51d40.firebasestorage.app',
    iosBundleId: 'com.example.walkathan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARXPnYGdsz4n-OE4SFJqJH7-6jgClOzOY',
    appId: '1:29862490445:web:b7ff0223db87b74b2f8704',
    messagingSenderId: '29862490445',
    projectId: 'walkathan-51d40',
    authDomain: 'walkathan-51d40.firebaseapp.com',
    storageBucket: 'walkathan-51d40.firebasestorage.app',
    measurementId: 'G-FCGE00JR8B',
  );

}